---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: awx
stringData:
  host: awx-postgres
  port: "5432"
  database: awx
  username: awx
  password: AnsibleRocks
  type: managed
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: awx-admin-password
  namespace: awx
stringData:
  password: AnsibleRocks
type: Opaque

# Add "awx-secret-tls" Secret by following the below steps for use of ingress.
# AWX_WEB_FQDN="fqdn.awx.host.com" <- Replace fqdn.awx.host.com with the host
# FQDN and DO NOT use IP.
# openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -out tls-cert.pem -keyout tls-key.pem -subj "/CN=${AWX_WEB_FQDN}/O=${AWX_WEB_FQDN}" -addext "subjectAltName = DNS:${AWX_WEB_FQDN}"
# kubectl -n awx create secret tls awx-secret-tls --cert=./tls-cert.pem --key=./tls-key.pem --dry-run=client -o yaml

